### ISSUE TITLE
I'm getting an error.  The game crashed whilst initializing game

### ISSUE THREAD

**Issue by tatsuki123321** [AbsolemJackdaw/PaintingsFabric#3]
I'm getting an error.

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'paintings'!

[crash-2021-08-27_22.36.55-client.txt](https://github.com/ArtixAllMighty/PaintingsFabric/files/7070365/crash-2021-08-27_22.36.55-client.txt)

**Comment by AbsolemJackdaw** [comment]
he log complains about this : 

illegal character in path at index 103: file:/D:/Users/E/AppData/Roaming/.minecraft/versions/1.17.1mod/./resourcepacks/Halcyon%20Days%20v1.2%20[1.6-1.7].zip

I'm guessing your json syntax is off. 
you can only use characters in this range : 
[a-z0-9/._-]

**Comment by AbsolemJackdaw** [comment]
Case closed as resolved due to lack of a response. 
version 1.0.0.1 equally has more aid in the logs for these errors now, 
as well as better crash handling
