### ISSUE TITLE
Server Crash. class cast exception

### ISSUE THREAD

**Issue by AbsolemJackdaw** [AbsolemJackdaw/PaintingsFabric#4]
Exit Code:

The game crashed whilst rendering screen
Error: java.lang.ClassCastException: class subaraki.paintings.gui.PaintingScreen cannot be cast to class subaraki.paintings.mixins.ScreenMixin (subaraki.paintings.gui.PaintingScreen and subaraki.paintings.mixins.ScreenMixin are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @4f0100a7)
Exit-Code: -1

**Comment by SplendidAlakey** [comment]
This also affects single-player.

[crash-2021-09-15_07.58.08-client.txt](https://github.com/ArtixAllMighty/PaintingsFabric/files/7167172/crash-2021-09-15_07.58.08-client.txt)

**Comment by AbsolemJackdaw** [comment]
crash is equally referenced in #6
