### ISSUE TITLE
I am having graphical issues with the Select Painting GUI.

### ISSUE THREAD

**Issue by asteroidb12** [AbsolemJackdaw/PaintingsFabric#6]
Whenever I place a painting, it only shows about 1 fourth of the selection screen.

Screenshot:
![2021-09-13_17 51 56](https://user-images.githubusercontent.com/68461874/133178130-51adb7e5-5916-4dae-9533-7b3e293950a9.png)

(may or may not be needed) modlist and log:
[mod list.txt](https://github.com/ArtixAllMighty/PaintingsFabric/files/7158241/mod.list.txt)
[latest.log](https://github.com/ArtixAllMighty/PaintingsFabric/files/7158243/latest.log)

**Comment by AbsolemJackdaw** [comment]
What i can currently tell is that 
"Dispenser Behavior 1.17-4.2.0-fabric" is terribly cluttering the log with spam. this is kinda unprofersionall imo. 
your 'Moar Paintings' pack isnt recognized as a paintings++ pack (no idea if that is okay or not)

apart from that, the log doesnt say anything obvious about rendering not working.

**Comment by AbsolemJackdaw** [comment]
i'm afraid you're going to have to take out a bunch of mods to see which one conflicts with paintings++.
i'd suggest removing all mods and making a test world. 
add paintings++ as sole mod, and half of your mods. 
if the mod works, restart the game, and add half of the mods that havent been added, untill it doesnt work anymorE. then you should be able to sus out one by one which mod is conflicting

please do report if you find what mod is conflicting, so we can try and solve the issue !

**Comment by asteroidb12** [comment]
Found out what mods are conflicting:
BetterUIScale and terraria-paintings

Better UI Scale causes most of the painting selection to be empty, there's no crash.
however, terraria paintings causes a crash which can be seen in this crash here:
[crash-2021-09-14_14.28.41-client.txt](https://github.com/ArtixAllMighty/PaintingsFabric/files/7165263/crash-2021-09-14_14.28.41-client.txt)

previous and latest log:
[2021-09-14-7.log](https://github.com/ArtixAllMighty/PaintingsFabric/files/7165287/2021-09-14-7.log)
[latest.log](https://github.com/ArtixAllMighty/PaintingsFabric/files/7165274/latest.log)


note: both were tested seperately, and "moar paintings" resource pack didn't load any new paintings even if it was activated.

**Comment by AbsolemJackdaw** [comment]
moar paintings is probably just a resourcepack to replace vanilla paintings with new textures.
also, the error regarding moar paintings points at the file not being a .zip file. is that possible ? 
should moar paintings be a paintings++ pack ? or not at all ? 

Better ui scale probably fiddles with the scaling of stuff, I'll try and check with the author. 

The crash seems to be a familiar one, I'll have Striker answer that one.

**Comment by asteroidb12** [comment]
the resource pack is a folder but not a zip, it probably doesn't work because of that.

**Comment by AbsolemJackdaw** [comment]
the crash has been fixed. the mod compat issue not yet. 
have you tried playing without better ui scale so far ?

**Comment by asteroidb12** [comment]
yeah, currently i don't have better ui scale

**Comment by Pi0nStEaM** [comment]
I do not know if I should open a new issue or not, but the selections from"terraria-paintings" won't show up in the gui.

**Comment by AbsolemJackdaw** [comment]
> I do not know if I should open a new issue or not, but the selections from"terraria-paintings" won't show up in the gui.

is it in any way related to this graphical glitch ? if not, make a new issue
try and check the [FAQ ](https://github.com/ArtixAllMighty/PaintingsFabric/wiki/FAQ)(which is slowly geting filled up with frequent questions)
