### ISSUE TITLE
Paintings don't match between clients on a server.

### ISSUE THREAD

**Issue by SplendidAlakey** [AbsolemJackdaw/PaintingsFabric#7]
**MC** 1.17.1
**Fabric API** fabric-api-0.40.1+1.17
**Paintings++** paintings-fabric-1.17.1-1.0.0.2

To reproduce, join a server and:

1. Let another player watch you
2. Place a painting on a wall
3. Choose any painting in the GUI

Expected result: the painting refreshes to what you've chosen for both of you.

Actual result: it only refreshes for the player who used the GUI. Other players will still see the picture that was initially placed.

**Comment by AbsolemJackdaw** [comment]
Striker, this sounds like a packet issue. could you look into it ?

**Comment by strikerrocker** [comment]
Fixed this issue. Thanks for reporting 👍
